export const FETCH_CAMPAIGNS_BY_PROJECTS_IDS_REQUEST = 'CAMPAIGNS_BY_PROJECTS_IDS.FETCH_REQUEST';
export const FETCH_CAMPAIGNS_BY_PROJECTS_IDS_FAILURE = 'CAMPAIGNS_BY_PROJECTS_IDS.FETCH_FAILURE';
export const FETCH_CAMPAIGNS_BY_PROJECTS_IDS_SUCCESS = 'CAMPAIGNS_BY_PROJECTS_IDS.FETCH_SUCCESS';
